version: '3'
services:
  react_app:
    container_name: application
    build:
      context: ./personal-website-fe
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      # - mail_server
      - blog_server
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app

  # mail_server:
  #   container_name: mail_server
  #   build:
  #     context: ./personal-website-fe
  #   command: node /app/src/server.js
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ${PWD}:/app

  mysql-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"


  blog_server:
    container_name: blog_server
    depends_on: 
      - mysql-db
    build:
      context: ./backend
    command: python3 manage.py runserver
    ports:
      - 8000:000
    volumes:
      - ${PWD}:/app

volumes:
  mysql_data: