# Generated by Django 4.1.4 on 2023-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageSrc',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQitsdSaPgiNoO7L6C4iZAGvjq6YS9AY6Hg1cepDNbvJA&s'),
        ),
    ]
