# Generated by Django 4.1.4 on 2023-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imagesrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageSrc',
            field=models.URLField(default='https://dummyimage.com/600x400/000/fff'),
        ),
    ]
