# Generated by Django 4.1.4 on 2023-01-12 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_category1_alter_post_category2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category3',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.date(2023, 1, 12)),
        ),
    ]
