# Generated by Django 4.1.4 on 2023-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(),
        ),
    ]
