# Generated by Django 4.1.4 on 2023-01-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='ContactUs',
        ),
    ]
